I thougt I made a lot of progress, but the OSGi bundle `org.eclipse.jdt.core` still does not load.
In particular, instead of trying to load my bundle that contains `com.bolinfest.jdt.MyActivator`,
I just tried to start the `org.eclipse.jdt.core` bundle, but I'm still hitting the "Workspace is closed"
issue:

```
$ ./scripts/run
Using buckd.
[-] PROCESSING BUCK FILES...FINISHED 0.2s
[-] BUILDING...FINISHED 0.0s (1/8 JOBS, 0 UPDATED)
!SESSION 2015-07-15 16:01:28.440 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.7.0_75
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Command-line arguments:  -consoleLog

!ENTRY org.eclipse.jdt.core 4 0 2015-07-15 16:01:29.007
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Exception in org.eclipse.jdt.core.JavaCore.start() of bundle org.eclipse.jdt.core.
				    at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:792)
				    at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
				    at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:941)
				    at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:318)
				    at org.eclipse.osgi.container.Module.doStart(Module.java:571)
				    at org.eclipse.osgi.container.Module.start(Module.java:439)
				    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
				    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
				    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
				    at org.eclipse.osgi.container.SystemModule.startWorker(SystemModule.java:242)
				    at org.eclipse.osgi.container.Module.doStart(Module.java:571)
				    at org.eclipse.osgi.container.Module.start(Module.java:439)
				    at org.eclipse.osgi.container.SystemModule.start(SystemModule.java:172)
				    at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:392)
				    at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:411)
				    at org.eclipse.osgi.launch.Equinox.start(Equinox.java:115)
				    at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:318)
				    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:231)
				    at org.eclipse.core.runtime.adaptor.EclipseStarter.main(EclipseStarter.java:208)
Caused by: java.lang.IllegalStateException: Workspace is closed.
       at org.eclipse.core.resources.ResourcesPlugin.getWorkspace(ResourcesPlugin.java:411)
       at org.eclipse.jdt.internal.core.JavaModelManager.shutdown(JavaModelManager.java:5060)
       at org.eclipse.jdt.internal.core.JavaModelManager.startup(JavaModelManager.java:5040)
       at org.eclipse.jdt.core.JavaCore.start(JavaCore.java:5704)
       at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
       at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
       at java.security.AccessController.doPrivileged(Native Method)
       at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
       ... 18 more
Root exception:
java.lang.IllegalStateException: Workspace is closed.
				 at org.eclipse.core.resources.ResourcesPlugin.getWorkspace(ResourcesPlugin.java:411)
				 at org.eclipse.jdt.internal.core.JavaModelManager.shutdown(JavaModelManager.java:5060)
				 at org.eclipse.jdt.internal.core.JavaModelManager.startup(JavaModelManager.java:5040)
				 at org.eclipse.jdt.core.JavaCore.start(JavaCore.java:5704)
				 at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
				 at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
				 at java.security.AccessController.doPrivileged(Native Method)
				 at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
				 at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
				 at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:941)
				 at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:318)
				 at org.eclipse.osgi.container.Module.doStart(Module.java:571)
				 at org.eclipse.osgi.container.Module.start(Module.java:439)
				 at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
				 at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
				 at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
				 at org.eclipse.osgi.container.SystemModule.startWorker(SystemModule.java:242)
				 at org.eclipse.osgi.container.Module.doStart(Module.java:571)
				 at org.eclipse.osgi.container.Module.start(Module.java:439)
				 at org.eclipse.osgi.container.SystemModule.start(SystemModule.java:172)
				 at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:392)
				 at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:411)
				 at org.eclipse.osgi.launch.Equinox.start(Equinox.java:115)
				 at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:318)
				 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:231)
				 at org.eclipse.core.runtime.adaptor.EclipseStarter.main(EclipseStarter.java:208)

!ENTRY org.eclipse.core.resources 4 0 2015-07-15 16:01:29.019
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Exception in org.eclipse.core.resources.ResourcesPlugin.start() of bundle org.eclipse.core.resources.
				    at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:792)
				    at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
				    at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:941)
				    at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:318)
				    at org.eclipse.osgi.container.Module.doStart(Module.java:571)
				    at org.eclipse.osgi.container.Module.start(Module.java:439)
				    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
				    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
				    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
				    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
				    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
				    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
				    at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
Caused by: org.eclipse.core.runtime.AssertionFailedException: assertion failed: The application has not been initialized.
       at org.eclipse.core.runtime.Assert.isTrue(Assert.java:110)
       at org.eclipse.core.internal.runtime.InternalPlatform.assertInitialized(InternalPlatform.java:139)
       at org.eclipse.core.internal.runtime.InternalPlatform.getStateLocation(InternalPlatform.java:541)
       at org.eclipse.core.runtime.Plugin.getStateLocation(Plugin.java:319)
       at org.eclipse.core.internal.resources.LocalMetaArea.<init>(LocalMetaArea.java:57)
       at org.eclipse.core.resources.ResourcesPlugin.start(ResourcesPlugin.java:455)
       at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
       at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
       at java.security.AccessController.doPrivileged(Native Method)
       at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
       ... 12 more
Root exception:
org.eclipse.core.runtime.AssertionFailedException: assertion failed: The application has not been initialized.
						   at org.eclipse.core.runtime.Assert.isTrue(Assert.java:110)
						   at org.eclipse.core.internal.runtime.InternalPlatform.assertInitialized(InternalPlatform.java:139)
						   at org.eclipse.core.internal.runtime.InternalPlatform.getStateLocation(InternalPlatform.java:541)
						   at org.eclipse.core.runtime.Plugin.getStateLocation(Plugin.java:319)
						   at org.eclipse.core.internal.resources.LocalMetaArea.<init>(LocalMetaArea.java:57)
						   at org.eclipse.core.resources.ResourcesPlugin.start(ResourcesPlugin.java:455)
						   at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
						   at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
						   at java.security.AccessController.doPrivileged(Native Method)
						   at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
						   at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
						   at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:941)
						   at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:318)
						   at org.eclipse.osgi.container.Module.doStart(Module.java:571)
						   at org.eclipse.osgi.container.Module.start(Module.java:439)
						   at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
						   at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
						   at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
						   at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
						   at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
						   at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
						   at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eclipse.osgi 4 0 2015-07-15 16:01:29.174
!MESSAGE Bundle org.eclipse.jdt.core_3.11.0.v20150126-2015 [2] is not active.
```